##
# This docker-compose file extends the default docker-compose.yml with
# **production** settings.
#
version: '2'
services:
  contract_observer:
    restart: on-failure

  etherdelta_observer:
    restart: on-failure

  huey_consumer:
    restart: on-failure

  websocket_server:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: api.${SERVERNAME}
      VIRTUAL_PORT: "8080"
    restart: on-failure

  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx # Need to name it in a specific way for nginx-dockergen to be able to restart it
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./etc/nginx/certs:/etc/nginx/certs:ro
      - ./etc/nginx/html:/usr/share/nginx/html

  # Service that updates nginx config to point to the right rails-app
  # containers, whenever they change.
  nginx-dockergen:
    image: jwilder/docker-gen # also alpine, if you're wondering
    container_name: nginx-dockergen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf /etc/nginx/vhost.d/
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx:/etc/docker-gen/templates/

  letsencrypt-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-dockergen
    volumes:
      - ./etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx

volumes:
  postgres-data:
